### ISSUE TITLE
improve speed of atom mapping

### ISSUE THREAD

**Issue by woodysherman** [stxinsite/atom_mapping#6]
The new atom mapping code is more accurate but takes a long time (~10 minutes per pair). The time seems to correlate with highly symmetric ligands that have multiple possible mappings. It should be possible to make this much faster.

**Comment by shuail** [comment]
After further cleaning up the code, I realized that this issue is more related to the disk IO between back end and front end. For the previous debugging purpose, there are lot of debugging info which will transfer from the backend to the front end which will slow down the speed dramatically. This should be fixed by this #9 . The maximum time I observed is ~2min per pair now.
